# -*- coding: utf-8 -*-
"""preprocessing0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_5JmOJZFkOLoA63Yw6MM1dGZWb4xlsSB
"""

import gzip
from google.colab import drive

drive.mount('/content/gdrive')

with gzip.open('gdrive/My Drive/Colab Notebooks/NOTEEVENTS.csv.gz', 'rt', newline='') as csv_file:
    csv_data = csv_file.read()
    with open('gdrive/My Drive/Colab Notebooks/NOTEEVENTS.csv', 'wt') as out_file:
         out_file.write(csv_data)

with gzip.open('gdrive/My Drive/Colab Notebooks/DIAGNOSES_ICD.csv.gz', 'rt', newline='') as csv_file:
    csv_data = csv_file.read()
    with open('gdrive/My Drive/Colab Notebooks/DIAGNOSES_ICD.csv', 'wt') as out_file:
         out_file.write(csv_data)